//go:build linux && ebpf

// Package bpf holds the eBPF magic-packet sensor: the compiled program bindings
// (generated by bpf2go from magicpacket.bpf.c) and a cilium/ebpf loader.
//
// EVERYTHING IN THIS PACKAGE IS BEHIND THE `ebpf` BUILD TAG, which the default
// egresswatch build never sets. So:
//   - `go build ./...` (no tags) is stdlib-only and needs no clang/cilium.
//   - the eBPF path is opted into explicitly with `-tags ebpf` on a Linux host
//     with a BTF kernel, after running `go generate ./bpf/...` to produce the
//     bindings. egresswatch ships the C source + this directive as artifacts and
//     never runs clang/bpf2go/the loader itself (see deploy/README.md).
//
// The generate directive below is SHOWN, NOT RUN by the build. bpf2go compiles
// magicpacket.bpf.c with clang and emits magicpacket_bpfel.go / _bpfeb.go plus
// the .o objects, all tagged for the matching endianness.
//
//	go install github.com/cilium/ebpf/cmd/bpf2go@latest
//	# vmlinux.h comes from: bpftool btf dump file /sys/kernel/btf/vmlinux format c > bpf/vmlinux.h
//	go generate ./bpf/...
//
//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc clang -target bpfel,bpfeb -cflags "-O2 -g -Wall" MagicPacket magicpacket.bpf.c
package bpf
