//go:build linux && ebpf

package bpf

import (
	"bytes"
	"context"
	"encoding/binary"
	"errors"
	"fmt"
	"os"

	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"
)

// Event mirrors `struct event` in magicpacket.bpf.c. It is the per-attach record
// the sensor emits when a process calls setsockopt(SO_ATTACH_FILTER) — the
// BPFDoor signature. Field order/sizes must match the C struct exactly.
type Event struct {
	PID      uint32
	TGID     uint32
	UID      uint32
	Level    int32
	Optname  int32
	Family   uint16
	IsPacket uint8
	_        uint8
	Comm     [16]byte
}

// CommString returns the null-trimmed process name.
func (e Event) CommString() string {
	if i := bytes.IndexByte(e.Comm[:], 0); i >= 0 {
		return string(e.Comm[:i])
	}
	return string(e.Comm[:])
}

// Sensor wraps the loaded objects, the attached tracepoint, and the ring buffer
// reader. It is the live counterpart to the periodic /proc triage: instead of
// catching an implant after the fact, it fires the instant one attaches a CBPF
// filter to a socket.
type Sensor struct {
	objs   MagicPacketObjects // generated by bpf2go (magicpacket_bpfel.go)
	tp     link.Link
	reader *ringbuf.Reader
}

// Load removes the memlock rlimit, loads the compiled objects, attaches the
// tracepoint, and opens the ring buffer. It requires CAP_BPF/CAP_SYS_ADMIN and a
// BTF-enabled kernel. egresswatch ships this code but never calls it without an
// operator explicitly running the `-tags ebpf` binary as root (deploy/README.md).
func Load() (*Sensor, error) {
	if err := rlimit.RemoveMemlock(); err != nil {
		return nil, fmt.Errorf("remove memlock: %w", err)
	}
	var objs MagicPacketObjects
	if err := LoadMagicPacketObjects(&objs, nil); err != nil {
		return nil, fmt.Errorf("load objects: %w", err)
	}
	tp, err := link.Tracepoint("syscalls", "sys_enter_setsockopt", objs.EgresswatchSetsockopt, nil)
	if err != nil {
		objs.Close()
		return nil, fmt.Errorf("attach tracepoint: %w", err)
	}
	rd, err := ringbuf.NewReader(objs.Events)
	if err != nil {
		tp.Close()
		objs.Close()
		return nil, fmt.Errorf("open ringbuf: %w", err)
	}
	return &Sensor{objs: objs, tp: tp, reader: rd}, nil
}

// Run reads events until ctx is cancelled, invoking handle for each. Closing the
// reader (via Close) unblocks the read with ringbuf.ErrClosed.
func (s *Sensor) Run(ctx context.Context, handle func(Event)) error {
	go func() {
		<-ctx.Done()
		_ = s.reader.Close()
	}()
	for {
		rec, err := s.reader.Read()
		if err != nil {
			if errors.Is(err, ringbuf.ErrClosed) {
				return nil
			}
			fmt.Fprintln(os.Stderr, "egresswatch: ringbuf read:", err)
			continue
		}
		var e Event
		if err := binary.Read(bytes.NewReader(rec.RawSample), binary.LittleEndian, &e); err != nil {
			continue
		}
		handle(e)
	}
}

// Close detaches the tracepoint and frees the maps/programs.
func (s *Sensor) Close() error {
	var errs []error
	if s.reader != nil {
		errs = append(errs, s.reader.Close())
	}
	if s.tp != nil {
		errs = append(errs, s.tp.Close())
	}
	errs = append(errs, s.objs.Close())
	return errors.Join(errs...)
}
